export const party = [
  {
    user: 'jason@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "Stigander Boerd",
    race: "aaracokra",
    level: "13",
    class: "Cleric",
    subClass: "Nature Domain",
    status: "Tripping",
    currHP: 92,
    maxHP: 92,
    AC:12,
    speed:30,
    proficiency:3,
    strength: 16,
    dexterity: 12,
    consitution: 14,
    intelligence: 13,
    wisdom: 20,
    charisma: 13,
    weapons: '{"heavy":[],"light":[],"reach":[],"thrown":[],"loading":[],"range":["bow"],"finesse":[],"special":[],"versatile":[],"twoHanded":[],"magicalWeapons":["scimitar","mustang & sally"]}',
    spells: '{"cantrips":["light","guidance","sacred flame","mending","druid craft","spare the dying"],"lvl1":["cure wounds","guiding bolt","santuary","healing word","bless","detect magic"],"lvl2":["prayer of healing","calm emotion","hold person","bark skin","spritual weapon"],"lvl3":["beacon of hope","revivify","spirit guardians","mass healing word","plant growth"],"lvl4":["death ward","divination","dominate beast","grasping vines","banishment"],"lvl5":["commune","flame strike","mass cure wounds"," geater restoration","planar binding"],"lvl6":["heal","word of recall","true seeing","blade barrier","plannar ally"],"lvl7":["conjure celestial","diving word","regenerate","plane shift","resurrection"],"lvl8":[],"lvl9":[]}',
    inventory: '{"everything":["mushroom pouch","bag of holding","silver dragon potion","magical cupcake","canteen of mushroom juice","a bunch of colored rocks"]}'
  },
  {
    user: 'david@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "Bojack",
    race: "Dark Elf",
    level: "12",
    class: "Monk",
    subClass: "Way of the Shadow",
    status: "unconscious",
    currHP: 22,
    maxHP: 74,
    AC:19,
    speed:45,
    proficiency:4,
    strength: 17,
    dexterity: 18,
    consitution: 12,
    intelligence: 12,
    wisdom: 10,
    charisma: 10,
    weapons: '{"heavy":[],"light":[],"reach":[],"thrown":[],"loading":[],"range":[],"finesse":[],"special":[],"versatile":[],"twoHanded":[],"magicalWeapons":[]}',
    spells: '{"cantrips":[],"lvl1":[],"lvl2":[],"lvl3":[],"lvl4":[],"lvl5":[],"lvl6":[],"lvl7":[],"lvl8":[],"lvl9":[]}',
    inventory: '{"everything":[]}'
  },
  {
    user: 'amanda@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "Malarie",
    race: "Elemental",
    level: "12",
    class: "Barbarian",
    subClass: "primal",
    status: "RAGING",
    currHP: 124,
    maxHP: 151,
    AC:16,
    speed:40,
    proficiency:5,
    strength: 20,
    dexterity: 14,
    consitution: 16,
    intelligence: 9,
    wisdom: 10,
    charisma: 11,
    weapons: '{"heavy":[],"light":[],"reach":[],"thrown":[],"loading":[],"range":["bow"],"finesse":[],"special":[],"versatile":[],"twoHanded":[],"magicalWeapons":["scimitar","mustang & sally"]}',
    spells: '{"cantrips":["light","guidance","sacred flame","mending","druid craft","spare the dying"],"lvl1":["cure wounds","guiding bolt","santuary","healing word","bless","detect magic"],"lvl2":["prayer of healing","calm emotion","hold person","bark skin","spritual weapon"],"lvl3":["beacon of hope","revivify","spirit guardians","mass healing word","plant growth"],"lvl4":["death ward","divination","dominate beast","grasping vines","banishment"],"lvl5":["commune","flame strike","mass cure wounds"," geater restoration","planar binding"],"lvl6":["heal","word of recall","true seeing","blade barrier","plannar ally"],"lvl7":["conjure celestial","diving word","regenerate","plane shift","resurrection"],"lvl8":[],"lvl9":[]}',
    inventory: '{"everything":["mushroom pouch","bag of holding","silver dragon potion","magical cupcake","canteen of mushroom juice","a bunch of colored rocks"]}'
  },
  {
    user: 'zeth@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "Zaris",
    race: "Dark Elf",
    level: "12",
    class: "Rogue",
    subClass: "Shadow",
    status: "hidden",
    currHP: 77,
    maxHP: 93,
    AC:19,
    speed:50,
    proficiency:8,
    strength: 18,
    dexterity: 20,
    consitution: 12,
    intelligence: 14,
    wisdom: 11,
    charisma: 15,
    weapons: '{"heavy":[],"light":[],"reach":[],"thrown":[],"loading":[],"range":["bow"],"finesse":[],"special":[],"versatile":[],"twoHanded":[],"magicalWeapons":["scimitar","mustang & sally"]}',
    spells: '{"cantrips":["light","guidance","sacred flame","mending","druid craft","spare the dying"],"lvl1":["cure wounds","guiding bolt","santuary","healing word","bless","detect magic"],"lvl2":["prayer of healing","calm emotion","hold person","bark skin","spritual weapon"],"lvl3":["beacon of hope","revivify","spirit guardians","mass healing word","plant growth"],"lvl4":["death ward","divination","dominate beast","grasping vines","banishment"],"lvl5":["commune","flame strike","mass cure wounds"," geater restoration","planar binding"],"lvl6":["heal","word of recall","true seeing","blade barrier","plannar ally"],"lvl7":["conjure celestial","diving word","regenerate","plane shift","resurrection"],"lvl8":[],"lvl9":[]}',
    inventory: '{"everything":["mushroom pouch","bag of holding","silver dragon potion","magical cupcake","canteen of mushroom juice","a bunch of colored rocks"]}'
  },
  {
    user: 'liz@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "tanwyn",
    race: "DragonBorn",
    level: "9",
    class: "Sorcerer",
    subClass: "draconic",
    status: "dead",
    currHP: 0,
    maxHP: 69,
    AC:12,
    speed:30,
    proficiency:3,
    strength: 9,
    dexterity: 8,
    consitution: 11,
    intelligence: 14,
    wisdom: 12,
    charisma: 10
  },
  {
    user: 'ariel@gmail.com',
    avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
    name: "Nekron",
    race: "DragonBorn",
    level: "11 + 3",
    class: "Paladin + Fighter",
    subClass: "Oath of Vengeance + Battle Master",
    status: "Defensive Position",
    currHP: 69,
    maxHP: 80,
    AC:22,
    speed:30,
    proficiency:4,
    strength: 16,
    dexterity: 12,
    consitution: 14,
    intelligence: 13,
    wisdom: 20,
    charisma: 13 
  },
  // {
  //   user: "",
  //   avatar: "https://howtodrawforkids.com/wp-content/uploads/2023/02/how-to-draw-a-mushroom.jpg",
  //   name: "",
  //   race: "",
  //   level: "",
  //   class: "",
  //   subClass: "",
  //   status: "",
  //   currHP: 0,
  //   maxHP: 0,
  //   AC:0,
  //   speed:0,
  //   proficiency:0
  // },
];

export const sessionDetails = {
  location1: 'mikes tavern',
  location2: 'town of ojalah',
  location3: 'dwarven kingdom',
  location4: 'athoria',
  time: 'sunset',
  weather: 'clear skies'
}

export const messages = [
  {
    name: "Stigander",
    action: "CASTED",
    actionName: "Healing Word",
    target: "everyone",
    rollMath: `roll(13) + widsomScore(8)`
  },
  {
    name: "Zaris",
    action: "ATTACKED",
    actionName: "dead dude dagger",
    target: "Dragon",
    rollMath: `roll(20) + stealth(5) + ice(6) + "the moon is out"(7) * backstab(2)`
  },
  {
    name: "Bojack",
    action: "ROLLED",
    actionName: "constitution save",
    target: "",
    rollMath: "roll(1)---lucky(7) + constitutionScore(2)",
  },
  {
    name: "Dragon",
    action: "TALKED",
    actionName: "",
    target: "goblin",
    dialog:"DONT JUST STAND THERE, DO SOMETHING",
    rollMath:""
  },
  {
    name: "Fizban",
    action: "TALKED",
    actionName: "",
    target: "Stigander",
    dialog:"a dragon hit the twin spires",
    rollMath:""
  },
  {
    name: "Stigander",
    action: "GAVE",
    actionName: "mushroom",
    target: "Zaris",
    dialog:"here stay safe",
    rollMath:"roll(2)"
  }
]