CREATE TABLE public.campaign_references (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, created_by uuid NOT NULL, kind text NOT NULL, name text NOT NULL, summary text DEFAULT ''::text NOT NULL, details text DEFAULT ''::text NOT NULL, status text DEFAULT 'active'::text NOT NULL, tags text[] DEFAULT '{}'::text[] NOT NULL, is_secret boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_details_check CHECK (char_length(details) <= 10000);
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_kind_check CHECK (kind = ANY (ARRAY['npc'::text, 'faction'::text, 'location'::text]));
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_name_check CHECK (char_length(name) >= 1 AND char_length(name) <= 160);
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_status_check CHECK (char_length(status) >= 1 AND char_length(status) <= 80);
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_summary_check CHECK (char_length(summary) <= 1000);
ALTER TABLE public.campaign_references ADD CONSTRAINT campaign_references_tags_check CHECK (cardinality(tags) <= 20);
REVOKE ALL ON TABLE public.campaign_references FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_references_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_references TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_references_id_seq TO authenticated;
CREATE INDEX campaign_references_created_by_idx ON public.campaign_references (created_by);
CREATE INDEX campaign_references_campaign_kind_idx ON public.campaign_references (campaign_id, kind, name);
CREATE TRIGGER campaign_references_set_updated_at BEFORE UPDATE ON public.campaign_references FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_references_delete_managers ON public.campaign_references FOR DELETE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_references.campaign_id) AS is_campaign_manager));
CREATE POLICY campaign_references_insert_managers ON public.campaign_references FOR INSERT TO authenticated WITH CHECK (((created_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_references.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_references_select_allowed ON public.campaign_references FOR SELECT TO authenticated USING ((( SELECT private.is_campaign_member(campaign_references.campaign_id) AS is_campaign_member) AND ((NOT is_secret) OR ( SELECT private.is_campaign_manager(campaign_references.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_references_update_managers ON public.campaign_references FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_references.campaign_id) AS is_campaign_manager)) WITH CHECK (( SELECT private.is_campaign_manager(campaign_references.campaign_id) AS is_campaign_manager));
