CREATE TABLE public.campaign_gm_states (campaign_id bigint NOT NULL, updated_by uuid NOT NULL, secret_state text DEFAULT ''::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_gm_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_gm_states ADD CONSTRAINT campaign_gm_states_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_gm_states ADD CONSTRAINT campaign_gm_states_pkey PRIMARY KEY (campaign_id);
ALTER TABLE public.campaign_gm_states ADD CONSTRAINT campaign_gm_states_secret_state_check CHECK (char_length(secret_state) <= 10000);
ALTER TABLE public.campaign_gm_states ADD CONSTRAINT campaign_gm_states_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
REVOKE ALL ON TABLE public.campaign_gm_states FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_gm_states TO authenticated;
CREATE INDEX campaign_gm_states_updated_by_idx ON public.campaign_gm_states (updated_by);
CREATE TRIGGER campaign_gm_states_set_updated_at BEFORE UPDATE ON public.campaign_gm_states FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_gm_states_delete_managers ON public.campaign_gm_states FOR DELETE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_gm_states.campaign_id) AS is_campaign_manager));
CREATE POLICY campaign_gm_states_insert_managers ON public.campaign_gm_states FOR INSERT TO authenticated WITH CHECK (((updated_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_gm_states.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_gm_states_select_managers ON public.campaign_gm_states FOR SELECT TO authenticated USING (( SELECT private.is_campaign_manager(campaign_gm_states.campaign_id) AS is_campaign_manager));
CREATE POLICY campaign_gm_states_update_managers ON public.campaign_gm_states FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_gm_states.campaign_id) AS is_campaign_manager)) WITH CHECK (((updated_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_gm_states.campaign_id) AS is_campaign_manager)));
CREATE TABLE public.campaign_objectives (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, created_by uuid NOT NULL, title text NOT NULL, description text DEFAULT ''::text NOT NULL, status text DEFAULT 'active'::text NOT NULL, priority text DEFAULT 'normal'::text NOT NULL, is_secret boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_description_check CHECK (char_length(description) <= 5000);
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text]));
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_status_check CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'failed'::text, 'abandoned'::text]));
ALTER TABLE public.campaign_objectives ADD CONSTRAINT campaign_objectives_title_check CHECK (char_length(title) >= 1 AND char_length(title) <= 160);
REVOKE ALL ON TABLE public.campaign_objectives FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_objectives_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_objectives TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_objectives_id_seq TO authenticated;
CREATE INDEX campaign_objectives_campaign_status_idx ON public.campaign_objectives (campaign_id, status, priority, updated_at DESC);
CREATE INDEX campaign_objectives_created_by_idx ON public.campaign_objectives (created_by);
CREATE TRIGGER campaign_objectives_set_updated_at BEFORE UPDATE ON public.campaign_objectives FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_objectives_delete_managers ON public.campaign_objectives FOR DELETE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_objectives.campaign_id) AS is_campaign_manager));
CREATE POLICY campaign_objectives_insert_managers ON public.campaign_objectives FOR INSERT TO authenticated WITH CHECK (((created_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_objectives.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_objectives_select_allowed ON public.campaign_objectives FOR SELECT TO authenticated USING ((( SELECT private.is_campaign_member(campaign_objectives.campaign_id) AS is_campaign_member) AND ((NOT is_secret) OR ( SELECT private.is_campaign_manager(campaign_objectives.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_objectives_update_managers ON public.campaign_objectives FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_objectives.campaign_id) AS is_campaign_manager)) WITH CHECK (( SELECT private.is_campaign_manager(campaign_objectives.campaign_id) AS is_campaign_manager));
CREATE TABLE public.campaign_world_states (campaign_id bigint NOT NULL, updated_by uuid NOT NULL, current_location text DEFAULT ''::text NOT NULL, in_world_datetime text DEFAULT ''::text NOT NULL, weather text DEFAULT ''::text NOT NULL, summary text DEFAULT ''::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_world_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_current_location_check CHECK (char_length(current_location) <= 200);
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_in_world_datetime_check CHECK (char_length(in_world_datetime) <= 200);
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_pkey PRIMARY KEY (campaign_id);
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_summary_check CHECK (char_length(summary) <= 5000);
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_world_states ADD CONSTRAINT campaign_world_states_weather_check CHECK (char_length(weather) <= 500);
REVOKE ALL ON TABLE public.campaign_world_states FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_world_states TO authenticated;
CREATE INDEX campaign_world_states_updated_by_idx ON public.campaign_world_states (updated_by);
CREATE TRIGGER campaign_world_states_set_updated_at BEFORE UPDATE ON public.campaign_world_states FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_world_states_delete_managers ON public.campaign_world_states FOR DELETE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_world_states.campaign_id) AS is_campaign_manager));
CREATE POLICY campaign_world_states_insert_managers ON public.campaign_world_states FOR INSERT TO authenticated WITH CHECK (((updated_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_world_states.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_world_states_select_members ON public.campaign_world_states FOR SELECT TO authenticated USING (( SELECT private.is_campaign_member(campaign_world_states.campaign_id) AS is_campaign_member));
CREATE POLICY campaign_world_states_update_managers ON public.campaign_world_states FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_world_states.campaign_id) AS is_campaign_manager)) WITH CHECK (((updated_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_world_states.campaign_id) AS is_campaign_manager)));
