CREATE TABLE public.campaign_inventory_items (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, created_by uuid NOT NULL, name text NOT NULL, description text DEFAULT ''::text NOT NULL, quantity integer DEFAULT 1 NOT NULL, unit text DEFAULT ''::text NOT NULL, category text DEFAULT 'other'::text NOT NULL, holder text DEFAULT 'Party'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_category_check CHECK (category = ANY (ARRAY['currency'::text, 'consumable'::text, 'equipment'::text, 'quest'::text, 'treasure'::text, 'other'::text]));
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_description_check CHECK (char_length(description) <= 2000);
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_holder_check CHECK (char_length(holder) >= 1 AND char_length(holder) <= 120);
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_name_check CHECK (char_length(name) >= 1 AND char_length(name) <= 160);
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_quantity_check CHECK (quantity >= 0 AND quantity <= 999999);
ALTER TABLE public.campaign_inventory_items ADD CONSTRAINT campaign_inventory_items_unit_check CHECK (char_length(unit) <= 40);
REVOKE ALL ON TABLE public.campaign_inventory_items FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_inventory_items_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_inventory_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_inventory_items_id_seq TO authenticated;
CREATE INDEX campaign_inventory_items_campaign_category_idx ON public.campaign_inventory_items (campaign_id, category, updated_at DESC);
CREATE INDEX campaign_inventory_items_created_by_idx ON public.campaign_inventory_items (created_by);
CREATE TRIGGER campaign_inventory_items_set_updated_at BEFORE UPDATE ON public.campaign_inventory_items FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_inventory_items_delete_members ON public.campaign_inventory_items FOR DELETE TO authenticated USING (( SELECT private.is_campaign_member(campaign_inventory_items.campaign_id) AS is_campaign_member));
CREATE POLICY campaign_inventory_items_insert_members ON public.campaign_inventory_items FOR INSERT TO authenticated WITH CHECK (((created_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_member(campaign_inventory_items.campaign_id) AS is_campaign_member)));
CREATE POLICY campaign_inventory_items_select_members ON public.campaign_inventory_items FOR SELECT TO authenticated USING (( SELECT private.is_campaign_member(campaign_inventory_items.campaign_id) AS is_campaign_member));
CREATE POLICY campaign_inventory_items_update_members ON public.campaign_inventory_items FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_member(campaign_inventory_items.campaign_id) AS is_campaign_member)) WITH CHECK (( SELECT private.is_campaign_member(campaign_inventory_items.campaign_id) AS is_campaign_member));
CREATE TABLE public.campaign_tasks (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, created_by uuid NOT NULL, assigned_to uuid, title text NOT NULL, description text DEFAULT ''::text NOT NULL, category text DEFAULT 'preparation'::text NOT NULL, status text DEFAULT 'todo'::text NOT NULL, due_at timestamp with time zone, is_gm_only boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_category_check CHECK (category = ANY (ARRAY['preparation'::text, 'downtime'::text]));
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_description_check CHECK (char_length(description) <= 3000);
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_status_check CHECK (status = ANY (ARRAY['todo'::text, 'in_progress'::text, 'done'::text]));
ALTER TABLE public.campaign_tasks ADD CONSTRAINT campaign_tasks_title_check CHECK (char_length(title) >= 1 AND char_length(title) <= 160);
REVOKE ALL ON TABLE public.campaign_tasks FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_tasks_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_tasks TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_tasks_id_seq TO authenticated;
CREATE INDEX campaign_tasks_assigned_to_idx ON public.campaign_tasks (assigned_to) WHERE assigned_to IS NOT NULL;
CREATE INDEX campaign_tasks_campaign_status_idx ON public.campaign_tasks (campaign_id, status, category, due_at);
CREATE INDEX campaign_tasks_created_by_idx ON public.campaign_tasks (created_by);
CREATE TRIGGER campaign_tasks_set_updated_at BEFORE UPDATE ON public.campaign_tasks FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_tasks_delete_author_or_manager ON public.campaign_tasks FOR DELETE TO authenticated USING (((created_by = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_campaign_manager(campaign_tasks.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_tasks_insert_allowed ON public.campaign_tasks FOR INSERT TO authenticated WITH CHECK (((created_by = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_member(campaign_tasks.campaign_id) AS is_campaign_member) AND ((NOT is_gm_only) OR ( SELECT private.is_campaign_manager(campaign_tasks.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_tasks_select_allowed ON public.campaign_tasks FOR SELECT TO authenticated USING ((( SELECT private.is_campaign_member(campaign_tasks.campaign_id) AS is_campaign_member) AND ((NOT is_gm_only) OR ( SELECT private.is_campaign_manager(campaign_tasks.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_tasks_update_allowed ON public.campaign_tasks FOR UPDATE TO authenticated USING (((created_by = ( SELECT auth.uid() AS uid)) OR (assigned_to = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_campaign_manager(campaign_tasks.campaign_id) AS is_campaign_manager))) WITH CHECK ((( SELECT private.is_campaign_member(campaign_tasks.campaign_id) AS is_campaign_member) AND ((NOT is_gm_only) OR ( SELECT private.is_campaign_manager(campaign_tasks.campaign_id) AS is_campaign_manager))));
