CREATE TABLE public.campaign_documents (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, author_id uuid NOT NULL, kind text DEFAULT 'note'::text NOT NULL, visibility text DEFAULT 'shared'::text NOT NULL, title text NOT NULL, body text DEFAULT ''::text NOT NULL, url text DEFAULT ''::text NOT NULL, is_pinned boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_body_check CHECK (char_length(body) <= 10000);
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_check CHECK (kind = 'note'::text OR url ~* '^https?://'::text);
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_kind_check CHECK (kind = ANY (ARRAY['note'::text, 'resource'::text]));
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_title_check CHECK (char_length(title) >= 1 AND char_length(title) <= 160);
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_url_check CHECK (char_length(url) <= 2000);
ALTER TABLE public.campaign_documents ADD CONSTRAINT campaign_documents_visibility_check CHECK (visibility = ANY (ARRAY['shared'::text, 'game_master'::text]));
REVOKE ALL ON TABLE public.campaign_documents FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_documents_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campaign_documents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_documents_id_seq TO authenticated;
CREATE INDEX campaign_documents_author_id_idx ON public.campaign_documents (author_id);
CREATE INDEX campaign_documents_campaign_visibility_idx ON public.campaign_documents (campaign_id, visibility, is_pinned DESC, updated_at DESC);
CREATE TRIGGER campaign_documents_set_updated_at BEFORE UPDATE ON public.campaign_documents FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY campaign_documents_delete_author_or_manager ON public.campaign_documents FOR DELETE TO authenticated USING (((author_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager)));
CREATE POLICY campaign_documents_insert_allowed ON public.campaign_documents FOR INSERT TO authenticated WITH CHECK (((author_id = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_member(campaign_documents.campaign_id) AS is_campaign_member) AND ((visibility = 'shared'::text) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager)) AND ((NOT is_pinned) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_documents_select_allowed ON public.campaign_documents FOR SELECT TO authenticated USING ((( SELECT private.is_campaign_member(campaign_documents.campaign_id) AS is_campaign_member) AND ((visibility = 'shared'::text) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager))));
CREATE POLICY campaign_documents_update_author_or_manager ON public.campaign_documents FOR UPDATE TO authenticated USING (((author_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager))) WITH CHECK ((( SELECT private.is_campaign_member(campaign_documents.campaign_id) AS is_campaign_member) AND ((author_id = ( SELECT auth.uid() AS uid)) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager)) AND ((visibility = 'shared'::text) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager)) AND ((NOT is_pinned) OR ( SELECT private.is_campaign_manager(campaign_documents.campaign_id) AS is_campaign_manager))));
