CREATE TABLE public.campaign_announcements (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, campaign_id bigint NOT NULL, author_id uuid NOT NULL, title text NOT NULL, body text NOT NULL, is_pinned boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.campaign_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_announcements ADD CONSTRAINT campaign_announcements_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_announcements ADD CONSTRAINT campaign_announcements_body_check CHECK (char_length(body) >= 1 AND char_length(body) <= 5000);
ALTER TABLE public.campaign_announcements ADD CONSTRAINT campaign_announcements_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_announcements ADD CONSTRAINT campaign_announcements_pkey PRIMARY KEY (id);
ALTER TABLE public.campaign_announcements ADD CONSTRAINT campaign_announcements_title_check CHECK (char_length(title) >= 1 AND char_length(title) <= 160);
REVOKE ALL ON TABLE public.campaign_announcements FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campaign_announcements_id_seq FROM anon, authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.campaign_announcements TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.campaign_announcements_id_seq TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.campaign_announcements TO service_role;
CREATE INDEX campaign_announcements_author_id_idx ON public.campaign_announcements (author_id);
CREATE INDEX campaign_announcements_campaign_pinned_idx ON public.campaign_announcements (campaign_id, is_pinned DESC, created_at DESC);
CREATE TRIGGER campaign_announcements_set_updated_at BEFORE UPDATE ON public.campaign_announcements FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY announcements_delete_managers ON public.campaign_announcements FOR DELETE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_announcements.campaign_id) AS is_campaign_manager));
CREATE POLICY announcements_insert_managers ON public.campaign_announcements FOR INSERT TO authenticated WITH CHECK (((author_id = ( SELECT auth.uid() AS uid)) AND ( SELECT private.is_campaign_manager(campaign_announcements.campaign_id) AS is_campaign_manager)));
CREATE POLICY announcements_select_members ON public.campaign_announcements FOR SELECT TO authenticated USING (( SELECT private.is_campaign_member(campaign_announcements.campaign_id) AS is_campaign_member));
CREATE POLICY announcements_update_managers ON public.campaign_announcements FOR UPDATE TO authenticated USING (( SELECT private.is_campaign_manager(campaign_announcements.campaign_id) AS is_campaign_manager)) WITH CHECK (( SELECT private.is_campaign_manager(campaign_announcements.campaign_id) AS is_campaign_manager));
