create table public.session_reaction_prompts (
 id bigint generated always as identity primary key, session_id bigint not null references public.sessions(id) on delete cascade, campaign_id bigint not null references public.campaigns(id) on delete cascade, character_id bigint not null references public.characters(id) on delete cascade, target_user_id uuid not null references public.profiles(id) on delete cascade, created_by uuid not null references public.profiles(id) on delete restrict, prompt text not null check(char_length(prompt) between 1 and 1000), status text not null default 'pending' check(status in ('pending','accepted','declined')), expires_at timestamptz not null, responded_at timestamptz, created_at timestamptz not null default now(), check(expires_at > created_at));
create index session_reaction_prompts_session_created_idx on public.session_reaction_prompts(session_id,created_at desc);
create index session_reaction_prompts_target_pending_idx on public.session_reaction_prompts(target_user_id,expires_at) where status='pending';
create index session_reaction_prompts_campaign_id_idx on public.session_reaction_prompts(campaign_id);
create index session_reaction_prompts_character_id_idx on public.session_reaction_prompts(character_id);
create index session_reaction_prompts_created_by_idx on public.session_reaction_prompts(created_by);
alter table public.session_reaction_prompts enable row level security;
create policy reaction_prompts_select_allowed on public.session_reaction_prompts for select to authenticated using(target_user_id=(select auth.uid()) or (select private.is_campaign_manager(campaign_id)));
create policy reaction_prompts_insert_managers on public.session_reaction_prompts for insert to authenticated with check(created_by=(select auth.uid()) and (select private.is_campaign_manager(campaign_id)) and status='pending' and responded_at is null and exists(select 1 from public.sessions where id=session_id and sessions.campaign_id=session_reaction_prompts.campaign_id and sessions.status='active') and exists(select 1 from public.characters where id=character_id and characters.campaign_id=session_reaction_prompts.campaign_id and characters.owner_id=target_user_id));
create function private.respond_reaction_prompt(requested_prompt_id bigint, should_accept boolean) returns public.session_reaction_prompts language plpgsql security definer set search_path='' as $$ declare target public.session_reaction_prompts; begin if (select auth.uid()) is null then raise exception 'Authentication is required.' using errcode='42501'; end if; select * into target from public.session_reaction_prompts where id=requested_prompt_id for update; if target.id is null or target.target_user_id<>(select auth.uid()) then raise exception 'Reaction prompt is unavailable.' using errcode='42501'; end if; if target.status<>'pending' or target.expires_at<=now() then raise exception 'Reaction prompt has expired or was already answered.' using errcode='P0001'; end if; update public.session_reaction_prompts set status=case when should_accept then 'accepted' else 'declined' end,responded_at=now() where id=target.id returning * into target; insert into public.session_events(session_id,campaign_id,actor_id,character_id,kind,visibility,title,body,metadata) values(target.session_id,target.campaign_id,target.target_user_id,target.character_id,'action','party',case when should_accept then 'Reaction accepted' else 'Reaction declined' end,target.prompt,jsonb_build_object('reaction_prompt_id',target.id,'accepted',should_accept)); return target; end; $$;
create function public.respond_reaction_prompt(prompt_id bigint, should_accept boolean) returns public.session_reaction_prompts language sql security invoker set search_path='' as $$ select private.respond_reaction_prompt(prompt_id,should_accept); $$;
revoke execute on function private.respond_reaction_prompt(bigint,boolean) from public,anon;
revoke execute on function public.respond_reaction_prompt(bigint,boolean) from public,anon;
grant execute on function private.respond_reaction_prompt(bigint,boolean) to authenticated;
grant execute on function public.respond_reaction_prompt(bigint,boolean) to authenticated;
grant select,insert on table public.session_reaction_prompts to authenticated;
grant usage,select on sequence public.session_reaction_prompts_id_seq to authenticated;
