CREATE TABLE public.characters (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, owner_id uuid NOT NULL, campaign_id bigint, name text NOT NULL, ancestry text DEFAULT ''::text NOT NULL, class_name text DEFAULT ''::text NOT NULL, subclass text DEFAULT ''::text NOT NULL, background text DEFAULT ''::text NOT NULL, level smallint DEFAULT 1 NOT NULL, armor_class smallint DEFAULT 10 NOT NULL, current_hp integer DEFAULT 1 NOT NULL, max_hp integer DEFAULT 1 NOT NULL, speed smallint DEFAULT 30 NOT NULL, strength smallint DEFAULT 10 NOT NULL, dexterity smallint DEFAULT 10 NOT NULL, constitution smallint DEFAULT 10 NOT NULL, intelligence smallint DEFAULT 10 NOT NULL, wisdom smallint DEFAULT 10 NOT NULL, charisma smallint DEFAULT 10 NOT NULL, notes text DEFAULT ''::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.characters ADD CONSTRAINT characters_ancestry_check CHECK (char_length(ancestry) <= 80);
ALTER TABLE public.characters ADD CONSTRAINT characters_armor_class_check CHECK (armor_class >= 0 AND armor_class <= 99);
ALTER TABLE public.characters ADD CONSTRAINT characters_background_check CHECK (char_length(background) <= 120);
ALTER TABLE public.characters ADD CONSTRAINT characters_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_charisma_check CHECK (charisma >= 1 AND charisma <= 30);
ALTER TABLE public.characters ADD CONSTRAINT characters_check CHECK (current_hp <= max_hp);
ALTER TABLE public.characters ADD CONSTRAINT characters_class_name_check CHECK (char_length(class_name) <= 80);
ALTER TABLE public.characters ADD CONSTRAINT characters_constitution_check CHECK (constitution >= 1 AND constitution <= 30);
ALTER TABLE public.characters ADD CONSTRAINT characters_current_hp_check CHECK (current_hp >= 0 AND current_hp <= 9999);
ALTER TABLE public.characters ADD CONSTRAINT characters_dexterity_check CHECK (dexterity >= 1 AND dexterity <= 30);
ALTER TABLE public.characters ADD CONSTRAINT characters_intelligence_check CHECK (intelligence >= 1 AND intelligence <= 30);
ALTER TABLE public.characters ADD CONSTRAINT characters_level_check CHECK (level >= 1 AND level <= 20);
ALTER TABLE public.characters ADD CONSTRAINT characters_max_hp_check CHECK (max_hp >= 1 AND max_hp <= 9999);
ALTER TABLE public.characters ADD CONSTRAINT characters_name_check CHECK (char_length(name) >= 1 AND char_length(name) <= 80);
ALTER TABLE public.characters ADD CONSTRAINT characters_notes_check CHECK (char_length(notes) <= 10000);
ALTER TABLE public.characters ADD CONSTRAINT characters_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.characters ADD CONSTRAINT characters_pkey PRIMARY KEY (id);
ALTER TABLE public.characters ADD CONSTRAINT characters_speed_check CHECK (speed >= 0 AND speed <= 999);
ALTER TABLE public.characters ADD CONSTRAINT characters_strength_check CHECK (strength >= 1 AND strength <= 30);
ALTER TABLE public.characters ADD CONSTRAINT characters_subclass_check CHECK (char_length(subclass) <= 80);
ALTER TABLE public.characters ADD CONSTRAINT characters_wisdom_check CHECK (wisdom >= 1 AND wisdom <= 30);
REVOKE ALL ON TABLE public.characters FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.characters_id_seq FROM anon, authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.characters TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.characters_id_seq TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.characters TO service_role;
CREATE INDEX characters_owner_id_idx ON public.characters (owner_id);
CREATE INDEX characters_campaign_id_idx ON public.characters (campaign_id) WHERE campaign_id IS NOT NULL;
CREATE TRIGGER characters_set_updated_at BEFORE UPDATE ON public.characters FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();
CREATE POLICY characters_delete_owner ON public.characters FOR DELETE TO authenticated USING ((owner_id = ( SELECT auth.uid() AS uid)));
CREATE POLICY characters_insert_owner ON public.characters FOR INSERT TO authenticated WITH CHECK (((owner_id = ( SELECT auth.uid() AS uid)) AND ((campaign_id IS NULL) OR ( SELECT private.is_campaign_member(characters.campaign_id) AS is_campaign_member))));
CREATE POLICY characters_select_owner_or_campaign_member ON public.characters FOR SELECT TO authenticated USING (((owner_id = ( SELECT auth.uid() AS uid)) OR ((campaign_id IS NOT NULL) AND ( SELECT private.is_campaign_member(characters.campaign_id) AS is_campaign_member))));
CREATE POLICY characters_update_owner ON public.characters FOR UPDATE TO authenticated USING ((owner_id = ( SELECT auth.uid() AS uid))) WITH CHECK (((owner_id = ( SELECT auth.uid() AS uid)) AND ((campaign_id IS NULL) OR ( SELECT private.is_campaign_member(characters.campaign_id) AS is_campaign_member))));
