ALTER TABLE public.characters ADD COLUMN pronouns text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_pronouns_check CHECK (char_length(pronouns) <= 80);
ALTER TABLE public.characters ADD COLUMN alignment text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_alignment_check CHECK (char_length(alignment) <= 80);
ALTER TABLE public.characters ADD COLUMN size text DEFAULT 'medium'::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_size_check CHECK (size = ANY (ARRAY['tiny'::text, 'small'::text, 'medium'::text, 'large'::text, 'huge'::text, 'gargantuan'::text]));
ALTER TABLE public.characters ADD COLUMN age text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_age_check CHECK (char_length(age) <= 80);
ALTER TABLE public.characters ADD COLUMN height text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_height_check CHECK (char_length(height) <= 80);
ALTER TABLE public.characters ADD COLUMN weight_lbs numeric(8,2);
ALTER TABLE public.characters ADD CONSTRAINT characters_weight_lbs_check CHECK (weight_lbs IS NULL OR weight_lbs >= 0::numeric AND weight_lbs <= 999999.99);
ALTER TABLE public.characters ADD COLUMN eyes text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_eyes_check CHECK (char_length(eyes) <= 80);
ALTER TABLE public.characters ADD COLUMN hair text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_hair_check CHECK (char_length(hair) <= 80);
ALTER TABLE public.characters ADD COLUMN skin text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_skin_check CHECK (char_length(skin) <= 80);
ALTER TABLE public.characters ADD COLUMN appearance text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_appearance_check CHECK (char_length(appearance) <= 5000);
ALTER TABLE public.characters ADD COLUMN biography text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_biography_check CHECK (char_length(biography) <= 20000);
ALTER TABLE public.characters ADD COLUMN personality_traits text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_personality_traits_check CHECK (char_length(personality_traits) <= 5000);
ALTER TABLE public.characters ADD COLUMN ideals text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_ideals_check CHECK (char_length(ideals) <= 5000);
ALTER TABLE public.characters ADD COLUMN bonds text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_bonds_check CHECK (char_length(bonds) <= 5000);
ALTER TABLE public.characters ADD COLUMN flaws text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_flaws_check CHECK (char_length(flaws) <= 5000);
ALTER TABLE public.characters ADD COLUMN allies_organizations text DEFAULT ''::text NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_allies_organizations_check CHECK (char_length(allies_organizations) <= 5000);
ALTER TABLE public.characters ADD COLUMN languages text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_languages_check CHECK (cardinality(languages) <= 50 AND char_length(array_to_string(languages, ','::text)) <= 2000);
ALTER TABLE public.characters ADD COLUMN senses text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.characters ADD CONSTRAINT characters_senses_check CHECK (cardinality(senses) <= 50 AND char_length(array_to_string(senses, ','::text)) <= 2000);
